### ISSUE TITLE
Parsing large delegates fails.

### ISSUE THREAD

**Issue by dr4cul4** [Virtuoze/CNeptune#1]
Hi it's me again.

I created a simple test assembly and managed to break the project.

```
using System;

namespace CNeptuneSample
{
    internal static class Program
    {
        private static int Main(string[] args)
        {
            Console.Out.WriteLine(new Sample().Sum(16, 6));
            Console.In.ReadLine();

            return 0;
        }
    }

    public class Sample
    {
        public float Sum(float a, float b)
        {
            return a + b;
        }
    }

    public delegate TResult Func<T1, TResult>(T1 arg1);

    // Above part works flawlessly, but this delegate brakes the system
    public delegate TResult Func<T1, T2, T3, T4, T5, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5);
}
```
Exception that is thrown (see comment in code):
```
System.ArgumentOutOfRangeException was unhandled
  HResult=-2146233086
  Message=Specified argument was out of the range of valid values.
  Source=Mono.Cecil
  StackTrace:
       w Mono.Collections.Generic.Collection`1.get_Item(Int32 index)
       w CNeptune.Program.Manage(TypeDefinition gateway, TypeDefinition authentic, FieldDefinition authority, MethodDefinition method) w C:\Development\Source\Tests\CNeptune-master\CNeptune\CNeptune\Program.cs:wiersz 215
       w CNeptune.Program.Manage(TypeDefinition gateway, TypeDefinition authentic) w C:\Development\Source\Tests\CNeptune-master\CNeptune\CNeptune\Program.cs:wiersz 89
       w CNeptune.Program.Manage(String assembly) w C:\Development\Source\Tests\CNeptune-master\CNeptune\CNeptune\Program.cs:wiersz 69
       w CNeptune.Program.Main(String[] arguments) w C:\Development\Source\Tests\CNeptune-master\CNeptune\CNeptune\Program.cs:wiersz 25
  InnerException: 
```

I will try to find more examples that breaks this approach.

Btw. This lib is better than obfuscation. dnSpy can't locate original code anywhere :D

Cheers

---
Edit: Unlocalize message in exception.

**Comment by dr4cul4** [comment]
Unfortunately first delegate (`public delegate TResult Func<T1, TResult>(T1 arg1);`) also breaks the assembly, but in a different way. 

When attempting to obfuscate assembly you get a index out of range. Commenting out this delegate solves the problem.

In mu opinion tempering with delegates should be avoided.

**Comment by Virtuoze** [comment]
Hi, sorry it is under development and currently unstable. 
Thank you for sharing this issue, It just means that I have to ignore some kind of class like delegate.

**Comment by dr4cul4** [comment]
Unfortunately latest version also crashes at similar place, namely Program.cs line 355 with the same exception as before.

**Comment by dr4cul4** [comment]
Maybe checking if type is inherited from System.Delegate and filtering it out would solve this issue

**Comment by Virtuoze** [comment]
Hi, 

I just tested it and it seems that delegate by-pass failed, so I changed it from 

`type.BaseType == type.Module.Import(typeof(MulticastDelegate));
`
to 

`(type.BaseType != null && type.BaseType.Resolve() == type.Module.Import(typeof(MulticastDelegate)).Resolve());`
