### ISSUE TITLE
3rd party assembly injection error

### ISSUE THREAD

**Issue by ismaelhamed** [Virtuoze/CNeptune#14]
If I try to run something like this from the cmd:

`CNeptune.exe "C:\...\bin\Debug\Newtonsoft.Json.dll" "Release"`

I get:

```
Unhandled Exception: System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at CNeptune.Program.Main(String[] arguments)
```

There must be something I'm missing, but it is not obvious to me.

**Comment by jho1965us** [comment]
you should either specify the dll file as a single argument or specify a project file and a configuration

so in your case 

    CNeptune.exe "C:\...\bin\Debug\Newtonsoft.Json.dll"

**Comment by ismaelhamed** [comment]
@jho1965us without the second argument it complains about the missing pdb, which I don't have in this case because it's a 3rd party assembly

**Comment by jho1965us** [comment]
@ismaelhamed I was not aware of that problem you could try use dotPeek to generate one
or change the following line in source

            var _assembly = AssemblyDefinition.ReadAssembly(assembly, new ReaderParameters() { AssemblyResolver = _resolver, ReadSymbols = true, ReadingMode = ReadingMode.Immediate });

to

            var _assembly = AssemblyDefinition.ReadAssembly(assembly, new ReaderParameters() { AssemblyResolver = _resolver, ReadSymbols = false, ReadingMode = ReadingMode.Immediate });

you will however likely run in to other problems see e.g. https://github.com/Virtuoze/CNeptune/issues/10
