### ISSUE TITLE
Request: support for OutputType=WinExe

### ISSUE THREAD

**Issue by jho1965us** [Virtuoze/CNeptune#5]
Got the following exception:
`
Unhandled Exception: System.NotSupportedException: Specified method is not supported.
    at CNeptune.Instrumentation.Program.Main(String[] arguments)
C:\Users\xx\Documents\Visual Studio 2017\Projects\...\packages\CNeptune.1.0.5\build\CNeptune.targets(10,9): error MSB3073: The command ""C:\Users\xx\Documents\Visual Studio 2017\Projects\...\packages\CNeptune.1.0.5\build\CNeptune.exe" "C:\Users\xx\Documents\Visual Studio 2017\Projects\...\WindowsFormsApplication1\WindowsFormsApplication1.csproj" "Debug"" exited with code -532462766.
`

May I also suggest that you add the following message to NotSupportedException: `$"Unknown OutputType: {_type.Value}"`

**Comment by Virtuoze** [comment]
Hi, you're right, I will add support for WinExe output type and add execption message for others.
I didn't find time to check if I had to do something special for WinExe, but it seems that nothing to do except manage it like Exe output type.

This changed is scheduled for few hours.

**Comment by Virtuoze** [comment]
Done.
CNeptune 1.0.6 is now available as nuget package.
