### ISSUE TITLE
Feature request proper handling of abstract methods

### ISSUE THREAD

**Issue by jho1965us** [Virtuoze/CNeptune#6]
Due to issue #5 I move my code to a library, for some reason I had to manual update the project with Import CNeptune etc. I  copied what was previous in the WinExe project file.
Now I get another runtime exception:
`
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
` 
LoaderExceptions are:
`
Could not load type '<Neptune>' from assembly 'Outliner, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' because the method '<get_Start>' has no implementation (no RVA).
`
and
`
Could not load type '<Neptune>' from assembly 'Outliner, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' because the method '<get_Name>' has no implementation (no RVA).
`
where Start is an abstract protected property to be weaved
and Name is an abstract public properties not to be weaved (changing them to public did not help)
my weaver code looks like this:
`
                Aspect.Weave<ParserAspect>(methodBase =>
        {
            if (methodBase.IsAbstract) return false;
            if (!typeof(Parser).IsAssignableFrom(methodBase.DeclaringType)) return false;
            var methodInfo = methodBase as MethodInfo;
            if (methodInfo == null) return false;
            if (!typeof(Term).IsAssignableFrom(methodInfo.ReturnType)) return false;
            Debug.WriteLine($"Weave {methodBase.DeclaringType}.{methodBase.Name}");
            return true;
        });
`
the exception happens before the pattern lambda has a chance to test IsAbstract and abort weaving of the method
changing the properties from abstract to virtual fix the problem

PS. I use NConcept to specify the weaving, VS2017 and is targeting .NET 4.5.2 framework

**Comment by Virtuoze** [comment]
Hi, 

Thank you again for reporting this issue, it seems that is not only for abstract methods.
Changing abstract to virtual seems to be the right think to fix your issue like you suggest but the real right fix is to simply ignore abstract method and let virtual dispatch do the job and jump to neptune pattern through implementions/inheritance.

Concerning NConcern, next week async methods will be managed and required to target at least .NET 4.5.2 too. Attaching aspect to abstract is not supported until full wrap for virtual method is release (see CNeptune roadmap)

**Comment by Virtuoze** [comment]
This issue is fixed with CNeptune 1.1.0
